module.exports = {
  //user list action
  USER_LIST: 'USER_LIST',
  USER_LIST_STARTED: 'USER_LIST_STARTED',
  USER_LIST_SUCCESS: 'USER_LIST_SUCCESS',
  USER_LIST_FAILED: 'USER_LIST_FAILED',
  UPDATE_STORE: 'UPDATE_STORE'
};
